import VDA5050.Basics.Enums

namespace VDA5050.Obligations
open VDA5050.Basics

inductive ErrorType
  | UNSUPPORTED_PARAMETER
  | NO_ORDER_TO_CANCEL
  | VALIDATION_FAILURE
  | INVALID_ORDER_ACTION
  | OTHER_ORDER_ACTIVE
  deriving Repr, DecidableEq

def errorLevel : ErrorType → ErrorLevel
  | .UNSUPPORTED_PARAMETER => .WARNING
  | .NO_ORDER_TO_CANCEL => .URGENT
  | .VALIDATION_FAILURE => .CRITICAL
  | .INVALID_ORDER_ACTION => .CRITICAL
  | .OTHER_ORDER_ACTIVE => .WARNING

end VDA5050.Obligations
