target_speed: 1.0

sensor: # fake camera
  max_range: 4.0
  fov_deg: 90.0

path:
  waypoints_x: [0, 3, 4, 6, 10, 11, 12, 6, 1, 0]
  waypoints_y: [0, 0, 2, 4, 3, 3, -1, -6, -2, -2]
  interpolation_step: 0.05

obstacles:
  - x: 3.3
    y: 0.55
    radius: 0.4

start:
  x: 0.0
  y: 0.3
  heading: 0.0
  velocity: 0.0

goal_threshold: 0.2
